### ISSUE TITLE
Github Actions gets ran twice for pull requests

### ISSUE THREAD

**Issue by lenilsonjr** [TokelPlatform/tokel_dapp#162]
## Expected Behavior

Test actions for each OS platform should only run once for PRs

## Current Behavior

Currently they get ran twice for each platform: 

<img width="944" alt="CleanShot 2021-11-02 at 14 10 25@2x" src="https://user-images.githubusercontent.com/3309021/139795182-23a06691-1b76-4d20-af1b-0808e42224d6.png">

## Possible Solution

We can adjust our test action to run on the following events:

```yaml
on:
  pull_request:
    branches: 
      - development
    types: [opened, synchronize, reopened, ready_for_review]
```
